#!/usr/bin/with-contenv sh

uid=${PUID:-1000}
user=$(getent passwd $uid | awk -F: '{print $1}')
if [ ! -f ${PLEX_AUTOSCAN_CONFIG} ]
then
    exec s6-setuidgid $user python3 /opt/plex_autoscan/scan.py sections
    echo "************************************************************************************"
    echo "INFO: Default ${PLEX_AUTOSCAN_CONFIG} generated, please configure for your environment. Exiting."
    echo "************************************************************************************"
    exit 1
elif grep -q '"PLEX_TOKEN": "",' ${PLEX_AUTOSCAN_CONFIG}
then
    echo "************************************************************************************"
    echo "ERROR: ${PLEX_AUTOSCAN_CONFIG} has not been configured, exiting."
    echo "************************************************************************************"
    exit 1
fi
exec s6-setuidgid $user python3 /opt/plex_autoscan/scan.py server
exit 0